name: CI

on:
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Nox
      run: pip install nox
    - name: Run Nox
      run: nox -s lint

  typechecking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Nox
      run: pip install nox
    - name: Run Nox
      run: nox -s mypy
